version: '3.8'

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: schedulerpass
      POSTGRES_DB: schedulerdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  postgres-data:
